KNOWN_PLATFORM_SOURCES = [
    {
        "source_type": "tg_cos",
        "name": "TG/COS 网络与终端平台",
        "vendor": "TG-NET",
        "base_url": "https://10.0.68.250/default.php",
        "management_ip": "10.0.68.250",
        "version": "V3.4.0-R220929",
        "notes": "只读事实源，掌握交换机、终端、摄像头、端口和告警关系。",
    },
    {
        "source_type": "jvss",
        "name": "富成视频监控集成平台",
        "vendor": "JVSS",
        "base_url": "http://10.0.59.200/jvss/sy_login.do",
        "management_ip": "10.0.59.200",
        "version": "audit-2026-04-09",
        "notes": "只读事实源，掌握 604 路通道、RTSP、快照、报警设备与报警点。",
    },
    {
        "source_type": "jvss",
        "name": "205分平台",
        "vendor": "JVSS",
        "base_url": "http://10.0.59.205/jvss/main.do",
        "management_ip": "10.0.59.205",
        "version": "audit-2026-04-09",
        "notes": "只读事实源，承接 205 分平台通道信息，其中 10.0.59 段以 B2 停车场为主，10.0.58 段属于商场视频区。",
    },
    {
        "source_type": "legacy_ops",
        "name": "旧视频运维系统告警桥接",
        "vendor": "Yongjia",
        "base_url": "",
        "management_ip": "127.0.0.1",
        "version": "1.1.1-bridge",
        "notes": "只读承接旧系统告警与闭环经验，用于 V2 过渡阶段归因展示。",
    },
    {
        "source_type": "gateway",
        "name": "开发主机出口网关",
        "vendor": "Ruijie Reyee",
        "base_url": "https://172.16.16.1",
        "management_ip": "172.16.16.1",
        "version": "ReyeeOS 2.340.0.2418",
        "notes": "开发主机所在边界网络出口设备，只读接入。",
    },
    {
        "source_type": "hikvision_nvr",
        "name": "电子城录像机 1",
        "vendor": "Hikvision",
        "base_url": "http://192.168.1.2/",
        "management_ip": "192.168.1.2",
        "version": "V4.74.210",
        "notes": "DS-8864N-R8，新海康 NVR。",
    },
    {
        "source_type": "hikvision_nvr",
        "name": "电子城录像机 2",
        "vendor": "Hikvision",
        "base_url": "http://192.168.1.3/",
        "management_ip": "192.168.1.3",
        "version": "V4.82.100",
        "notes": "DS-8864N-R8(B)，新海康 NVR。",
    },
    {
        "source_type": "hikvision_decoder",
        "name": "海康解码器",
        "vendor": "Hikvision",
        "base_url": "https://192.168.1.5/",
        "management_ip": "192.168.1.5",
        "version": "V3.6.2",
        "notes": "DS-6404HD-T，老解码器，只读接入。",
    },
    {
        "source_type": "hikvision_nvr",
        "name": "尚品天成车场 1",
        "vendor": "Hikvision",
        "base_url": "http://192.168.5.253/",
        "management_ip": "192.168.5.253",
        "version": "V4.82.100",
        "notes": "DS-8864N-R8(B)，车场 NVR。",
    },
    {
        "source_type": "hikvision_nvr",
        "name": "尚品天成车场 2",
        "vendor": "Hikvision",
        "base_url": "http://192.168.5.254/",
        "management_ip": "192.168.5.254",
        "version": "V4.82.100",
        "notes": "DS-8864N-R8(B)，车场 NVR。",
    },
    {
        "source_type": "hikvision_nvr",
        "name": "书城录像机 1",
        "vendor": "Hikvision",
        "base_url": "http://192.168.6.2/",
        "management_ip": "192.168.6.2",
        "version": "V3.4.106",
        "notes": "DS-7916N-E4，老海康 NVR。",
    },
    {
        "source_type": "hikvision_nvr",
        "name": "书城录像机 2",
        "vendor": "Hikvision",
        "base_url": "http://192.168.6.3/",
        "management_ip": "192.168.6.3",
        "version": "V3.4.106",
        "notes": "DS-7932N-E4，老海康 NVR。",
    },
    {
        "source_type": "control_platform_new",
        "name": "风控电控新平台",
        "vendor": "Unknown",
        "base_url": "",
        "management_ip": "pending-new",
        "version": "pending-intake",
        "notes": "明日待接入的新控制平台，先占位为只读事实源。",
    },
    {
        "source_type": "control_platform_legacy",
        "name": "风控电控老平台",
        "vendor": "Unknown",
        "base_url": "",
        "management_ip": "pending-legacy",
        "version": "pending-intake",
        "notes": "明日待接入的老控制平台，先占位为只读事实源。",
    },
]


KNOWN_DEVICES = [
    {
        "device_type": "platform_node",
        "vendor": "TG-NET",
        "model": "TG/COS",
        "hostname": "TG/COS 网络与终端平台",
        "management_ip": "10.0.68.250",
        "service_ip": "10.0.68.250",
        "serial_number": "",
        "primary_source_type": "tg_cos",
        "notes": "只读事实源平台节点。",
    },
    {
        "device_type": "platform_node",
        "vendor": "JVSS",
        "model": "JVSS Main",
        "hostname": "富成视频监控集成平台",
        "management_ip": "10.0.59.200",
        "service_ip": "10.0.59.200",
        "serial_number": "",
        "primary_source_type": "jvss",
        "notes": "只读事实源平台节点。",
    },
    {
        "device_type": "platform_node",
        "vendor": "JVSS",
        "model": "JVSS Stream",
        "hostname": "205分平台",
        "management_ip": "10.0.59.205",
        "service_ip": "10.0.59.205",
        "serial_number": "",
        "primary_source_type": "jvss",
        "notes": "只读事实源平台节点，当前承接 205 分平台视频通道，59 段以 B2 停车场为主，58 段属于商场视频区。",
    },
    {
        "device_type": "gateway",
        "vendor": "Ruijie Reyee",
        "model": "RG-EG105G V2",
        "hostname": "开发主机出口网关",
        "management_ip": "172.16.16.1",
        "service_ip": "172.16.16.1",
        "serial_number": "H1UUBGV004267",
        "primary_source_type": "gateway",
        "notes": "开发主机所在出口网关。",
    },
    {
        "device_type": "nvr",
        "vendor": "Hikvision",
        "model": "DS-8864N-R8",
        "hostname": "电子城录像机 1",
        "management_ip": "192.168.1.2",
        "service_ip": "192.168.1.2",
        "serial_number": "DS-8864N-R81620221223CCRRL07961438WCVU",
        "primary_source_type": "hikvision_nvr",
        "notes": "新 NVR，审计确认支持 ISAPI。",
    },
    {
        "device_type": "nvr",
        "vendor": "Hikvision",
        "model": "DS-8864N-R8(B)",
        "hostname": "电子城录像机 2",
        "management_ip": "192.168.1.3",
        "service_ip": "192.168.1.3",
        "serial_number": "DS-8864N-R8(B)1620221220CCRRL06420286WCVU",
        "primary_source_type": "hikvision_nvr",
        "notes": "新 NVR，审计确认支持 ISAPI。",
    },
    {
        "device_type": "decoder",
        "vendor": "Hikvision",
        "model": "DS-6404HD-T",
        "hostname": "海康解码器",
        "management_ip": "192.168.1.5",
        "service_ip": "192.168.1.5",
        "serial_number": "DS-6404HD-T0120170331BBRR741370426WC",
        "primary_source_type": "hikvision_decoder",
        "notes": "老解码器，DisplayModeSupport=true。",
    },
    {
        "device_type": "nvr",
        "vendor": "Hikvision",
        "model": "DS-8864N-R8(B)",
        "hostname": "尚品天成车场 1",
        "management_ip": "192.168.5.253",
        "service_ip": "192.168.5.253",
        "serial_number": "DS-8864N-R8(B)1620221224CCRRL13074505WCVU",
        "primary_source_type": "hikvision_nvr",
        "notes": "车场新 NVR。",
    },
    {
        "device_type": "nvr",
        "vendor": "Hikvision",
        "model": "DS-8864N-R8(B)",
        "hostname": "尚品天成车场 2",
        "management_ip": "192.168.5.254",
        "service_ip": "192.168.5.254",
        "serial_number": "DS-8864N-R8(B)1620230115CCRRL19018617WCVU",
        "primary_source_type": "hikvision_nvr",
        "notes": "车场新 NVR。",
    },
    {
        "device_type": "nvr",
        "vendor": "Hikvision",
        "model": "DS-7916N-E4",
        "hostname": "书城录像机 1",
        "management_ip": "192.168.6.2",
        "service_ip": "192.168.6.2",
        "serial_number": "DS-7916N-E41620150611AARR523570034WCVU",
        "primary_source_type": "hikvision_nvr",
        "notes": "老 NVR，兼容接入对象。",
    },
    {
        "device_type": "nvr",
        "vendor": "Hikvision",
        "model": "DS-7932N-E4",
        "hostname": "书城录像机 2",
        "management_ip": "192.168.6.3",
        "service_ip": "192.168.6.3",
        "serial_number": "DS-7932N-E41620150630AARR526277302WCVU",
        "primary_source_type": "hikvision_nvr",
        "notes": "老 NVR，兼容接入对象。",
    },
    {
        "device_type": "platform_node",
        "vendor": "Unknown",
        "model": "Control Platform",
        "hostname": "风控电控新平台",
        "management_ip": "pending-new",
        "service_ip": "pending-new",
        "serial_number": "",
        "primary_source_type": "control_platform_new",
        "notes": "明日待接入的新控制平台占位节点，只读事实源。",
    },
    {
        "device_type": "platform_node",
        "vendor": "Unknown",
        "model": "Control Platform",
        "hostname": "风控电控老平台",
        "management_ip": "pending-legacy",
        "service_ip": "pending-legacy",
        "serial_number": "",
        "primary_source_type": "control_platform_legacy",
        "notes": "明日待接入的老控制平台占位节点，只读事实源。",
    },
]
